language: python
python:
  - "2.6"
  - "2.7"
#  - "3.2"
env:
  - DJANGO_VERSION=1.4.5
  - DJANGO_VERSION=1.3.7
  - DJANGO_VERSION=1.5.1

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q -r requirements.txt
  - pip install -q pytz
  - python setup.py -q install
script:
  - python setup.py test
